<?php
declare(strict_types=1);

/**
 * Pares placa / operador logístico (COLBEEF).
 * Generado con: php scripts/sync_placas_from_xlsx.php
 * Listado principal: tabla PostgreSQL `despacho_operador_placas`.
 */
return [
    'filas' => [
        ['placa' => 'SYU 534', 'operador' => 'AHU.ORIENTE'],
        ['placa' => 'ZZZ111', 'operador' => 'COLBEEF'],
        ['placa' => 'ESK381', 'operador' => 'INST-COMERCIBEEF'],
        ['placa' => 'TAX 512', 'operador' => 'DISCARSAN'],
        ['placa' => 'EQT 164', 'operador' => 'REG-DISTRISERVIX'],
        ['placa' => 'EQT164', 'operador' => 'REG-DISTRISERVIX'],
        ['placa' => 'SOE773', 'operador' => 'GRANJA PAISA'],
        ['placa' => 'SWL884', 'operador' => 'INST'],
        ['placa' => 'SXS722', 'operador' => 'INST'],
        ['placa' => 'LWY646', 'operador' => 'INST.KOBE'],
        ['placa' => 'WOL560', 'operador' => 'INST.OFACOL'],
        ['placa' => 'JUN840', 'operador' => 'INST.PETRO'],
        ['placa' => 'EQO018', 'operador' => 'INST.PETRO'],
        ['placa' => 'LUK766', 'operador' => 'INST.PETRO'],
        ['placa' => 'ESQ 155', 'operador' => 'INST-BUFASAN'],
        ['placa' => 'SXS722', 'operador' => 'INST-CPT'],
        ['placa' => 'XMC198', 'operador' => 'INST-CPT'],
        ['placa' => 'TTR556', 'operador' => 'INST-CPT'],
        ['placa' => 'SYR693', 'operador' => 'INST-MULTICARNES'],
        ['placa' => 'TTV831', 'operador' => 'INST-MULTICARNES'],
        ['placa' => 'TTS 460', 'operador' => 'INST-MULTICARNES'],
        ['placa' => 'WOK 691', 'operador' => 'INST-MULTICARNES'],
        ['placa' => 'LCM829', 'operador' => 'INST-MXM'],
        ['placa' => 'WFD 815', 'operador' => 'INST-OLIMPICA'],
        ['placa' => 'LPL326', 'operador' => 'INST-OLIMPICA'],
        ['placa' => 'WNZ798', 'operador' => 'INST-OLIMPICA'],
        ['placa' => 'TTG 425', 'operador' => 'INST-OLIMPICA'],
        ['placa' => 'XVW170', 'operador' => 'INST-OLIMPICA'],
        ['placa' => 'XVW 170', 'operador' => 'INST-OLIMPICA'],
        ['placa' => 'TTR892', 'operador' => 'INST-SANTACRUZ'],
        ['placa' => 'TTR  893', 'operador' => 'INST-SANTACRUZ'],
        ['placa' => 'LPL015', 'operador' => 'INST-ZULUAGA'],
        ['placa' => 'XVY016', 'operador' => 'INST-ZULUAGA'],
        ['placa' => 'TTU548', 'operador' => 'JUAN RUEDA'],
        ['placa' => 'JOW077', 'operador' => 'L-QUIROGA'],
        ['placa' => 'GQW329', 'operador' => 'L-QUIROGA'],
        ['placa' => 'TLQ176', 'operador' => 'L-QUIROGA'],
        ['placa' => 'TTV096', 'operador' => 'MANZANARES'],
        ['placa' => 'JUN825', 'operador' => 'NACIONAL EL SEÑOR DE LAS CARNES'],
        ['placa' => 'XVI 994', 'operador' => 'OTROS'],
        ['placa' => 'SXT436', 'operador' => 'OTROS'],
        ['placa' => 'XVL610', 'operador' => 'OTROS'],
        ['placa' => 'WNZ018', 'operador' => 'OTROS'],
        ['placa' => 'LUW977', 'operador' => 'OTROS'],
        ['placa' => 'XVP 631', 'operador' => 'OTROS'],
        ['placa' => 'WMQ364', 'operador' => 'OTROS'],
        ['placa' => 'LZK462', 'operador' => 'OTROS'],
        ['placa' => 'GQU181', 'operador' => 'OTROS'],
        ['placa' => 'TTS460', 'operador' => 'OTROS'],
        ['placa' => 'SXR854', 'operador' => 'OTROS'],
        ['placa' => 'SZS831', 'operador' => 'OTROS'],
        ['placa' => 'LPM273', 'operador' => 'PART-AJR'],
        ['placa' => 'WFD 008', 'operador' => 'PART-AJR'],
        ['placa' => 'TPW108', 'operador' => 'INST-OLIMPICA'],
        ['placa' => 'HHD03C', 'operador' => 'OTROS'],
        ['placa' => 'WOL 870', 'operador' => 'OTROS'],
        ['placa' => 'LPL051', 'operador' => 'PART-EDGAR AM'],
        ['placa' => 'LPL364', 'operador' => 'PART-CEBU'],
        ['placa' => 'LTL 364', 'operador' => 'PART-CEBU'],
        ['placa' => 'WFG268', 'operador' => 'INST-COMERCIBEEF'],
        ['placa' => 'NNL738', 'operador' => 'PART-DRA'],
        ['placa' => 'NNL739', 'operador' => 'PART-DRA'],
        ['placa' => 'JTY987', 'operador' => 'PART-DRA'],
        ['placa' => 'WOK638', 'operador' => 'PART-DRA'],
        ['placa' => 'TTR 662', 'operador' => 'PART-EL PALACIO'],
        ['placa' => 'SBL103', 'operador' => 'PART-GUACA'],
        ['placa' => 'JVK588', 'operador' => 'PART-JIMENEZ'],
        ['placa' => 'TAW734', 'operador' => 'PART-MIREYA'],
        ['placa' => 'WFC 318', 'operador' => 'PART-TA'],
        ['placa' => 'SXG533', 'operador' => 'PART-TA'],
        ['placa' => 'LWY718', 'operador' => 'PART-VILLANUEVA'],
        ['placa' => 'GQU 042', 'operador' => 'PART-WO'],
        ['placa' => 'LPM202', 'operador' => 'PART-WO'],
        ['placa' => 'WOK 733', 'operador' => 'REG-DISTRISERVIX'],
        ['placa' => 'SRS462', 'operador' => 'REG-DISTRISERVIX'],
        ['placa' => 'TSW518', 'operador' => 'REGIONAL'],
        ['placa' => 'MYW766', 'operador' => 'REGIONAL'],
        ['placa' => 'SXD756', 'operador' => 'SUBCARNES'],
        ['placa' => 'SVM630', 'operador' => 'PART-CAMILO'],
        ['placa' => 'LPK762', 'operador' => 'PART-YERSON'],
        ['placa' => 'LPL684', 'operador' => 'PART-YERSON'],
        ['placa' => 'WOM497', 'operador' => 'INST-MULTICARNES'],
        ['placa' => 'TBZ171', 'operador' => 'PART-MIREYA'],
        ['placa' => 'GQU920', 'operador' => 'REG-ELCEBU'],
        ['placa' => 'LPM439', 'operador' => 'TRANSCARNES'],
        ['placa' => 'FSV662', 'operador' => 'TRANSCARNES'],
        ['placa' => 'WTL 507', 'operador' => 'TRANSCARNES'],
        ['placa' => 'TTT078', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SMT404', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SMT478', 'operador' => 'TRANSCARNES'],
        ['placa' => 'XVW 474', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SOZ304', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SOZ 369', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SOZ 372', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SUF137', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SXT 135', 'operador' => 'TRANSCARNES'],
        ['placa' => 'USC 289', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SXT137', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SXT 136', 'operador' => 'TRANSCARNES'],
        ['placa' => 'TAX 284', 'operador' => 'TRANSCARNES'],
        ['placa' => 'TAX140', 'operador' => 'TRANSCARNES'],
        ['placa' => 'TTR605', 'operador' => 'TRANSCARNES'],
        ['placa' => 'WFC808', 'operador' => 'TRANSCARNES'],
        ['placa' => 'WFD008', 'operador' => 'PART-AJR'],
        ['placa' => 'WFD530', 'operador' => 'TRANSCARNES'],
        ['placa' => 'XVW474', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SKX332', 'operador' => 'TRANSCARNES'],
        ['placa' => 'WCX520', 'operador' => 'TRANSCARNES'],
        ['placa' => 'WFD854', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SOZ726', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SOZ305', 'operador' => 'TRANSCARNES'],
        ['placa' => 'TTU547', 'operador' => 'TRANSCARNES'],
        ['placa' => 'SOZ238', 'operador' => 'TRANSCARNES'],
        ['placa' => 'USB 866', 'operador' => 'OTROS'],
    ],
];
